### ISSUE TITLE
Support for v3 onions?

### ISSUE THREAD

**Issue by gitbugged** [dirtyfilthy/freshonions-torscraper#10]
Great work on this project. Just wondering if you plan to add support for the new v3 onions, which contain a much longer in address.

**Comment by BossMAN559** [comment]
the copy that i am running already lists V3 addresses.
guess it just needs to be published on a V3 address and it starts getting them.

**Comment by MrL3X** [comment]
I did the update, you can look at this readme file and go in the section `Tor`, it will talk about how to support the V3. I also mentioned test in the `Start your services` section that you should do to be sure it's supporting V3 onions. If you have problems just let me know ;) 

Readme link : https://github.com/GoSecure/freshonions-torscraper/blob/update-readme/README.md

**Comment by L3houx** [comment]
Hey @gitbugged , if I answered your question, you can close this ticket. 

Thank you

**Comment by gitbugged** [comment]
Thanks, that solves it.
