### ISSUE TITLE
onion is down, any possibility of it going up again?

### ISSUE THREAD

**Issue by muphenmahn** [dirtyfilthy/freshonions-torscraper#30]
i miss this shit..any way to contribute?

**Comment by L3houx** [comment]
Hi @muphenmahn, 

If you want to contribute, look at our fork: https://github.com/GoSecure/freshonions-torscraper. I added several functionalities that the original didn't have. Also, it looks like this project is dead, the maintainer did answer to my PR, so if you have questions, let's ask on our issues.

**Comment by muphenmahn** [comment]
Thanks man

**Comment by L3houx** [comment]
You can close this issue if I answered your questions.

**Comment by muphenmahn** [comment]
Well you didnt really do anything except tell me about your fork, so i will leave it open. Maybe lil less sass next time.
