### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by kenkit** [dirtyfilthy/freshonions-torscraper#9]
I've just installed everything, but the readme is not upto date.

**Comment by gitbugged** [comment]
Since you've done it, maybe you could consider sending a Pull Request? Would help others like myself interested in this project.

**Comment by kenkit** [comment]
I never did manage to do finish it, I've been waiting to find free time to try it again.

**Comment by MrL3X** [comment]
I update the readme to be able to follow only the readme and all should be good. This is the link of the updated ReadMe : https://github.com/GoSecure/freshonions-torscraper/blob/update-readme/README.md

**Comment by kenkit** [comment]
nice.
